[package]
name = "ferrite-book"
version = "0.1.0"
authors = ["Soares Chen <soares.chen@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
tokio = { version = "1.5.0" }
ferrite-session = { version = "0.1.3" }
