[package]
name = "ferrite-book"
version = "0.1.0"
authors = ["Soares Chen <soares.chen@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
ferrite-session = { version = "0.1.0" }
async-std = { version = "1.6.5", features = ["attributes"] }