name: github pages

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run tests
        run: cd code && cargo test
